import Head from 'next/head'
import Container from '../components/Container'

export default function Home() {
  return (
    <div className='w-full h-auto m-0 bg-zinc-800'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container />
    </div>
  )
}
